version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./:/var/www/html
    working_dir: /var/www/html
